name: Build and Push Docker Image
on:
  workflow_dispatch:
  push:
    paths:
      - "**/Dockerfile"

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/dgatdo-application:latest
